Lab01
bodnarira/SA pull request #4
Opened 2019-10-22 19:37 UTC by bodnarira

2019-10-23 11:11 UTC, polyakovartem commented
please ask your colleagues to comment on this lab

2019-10-23 17:25 UTC, bodnarira commented
> please ask your colleagues to comment on this lab

My colleagues said that everything is right in code

2019-10-24 10:27 UTC, polyakovartem requested changes
https://docs.python.org/3/library/__main__.html

2019-10-24 10:27 UTC, polyakovartem commented on lab01.py
> +main(5)
https://docs.python.org/3/library/__main__.html

2019-10-24 12:45 UTC, polyakovartem approved these changes

2023-04-27 09:34 UTC, closed without merging