Lab08
bodnarira/SA pull request #9
Opened 2019-11-11 20:53 UTC by bodnarira

2019-11-12 09:43 UTC, polyakovartem requested changes

2019-11-12 09:43 UTC, polyakovartem commented on Lab08.py
> +    def duplicates (self):
please split this function, the logic is to complex for one function

2019-11-12 09:43 UTC, polyakovartem commented on Lab08.py
> +print(dir.duplicates())
where is __main__ ?

2019-11-12 09:44 UTC, polyakovartem requested changes
by the way, I've already seen this code by your colleagues, could you please explain how did it happen?

2019-11-12 22:22 UTC, bodnarira commented
> by the way, I've already seen this code by your colleagues, could you please explain how did it happen?

Send me a link of this code you have seen.

2019-11-12 22:23 UTC, bodnarira commented on Lab08.py
> +print(dir.duplicates())
ok

2019-11-13 07:23 UTC, polyakovartem requested changes
could you kindly explain why you did not fix other comments?

2019-11-13 07:24 UTC, polyakovartem commented on Lab08.py
> +    dir = Dir("D:/Ira/Python/new/")
it's not the best idea to use absolute paths in the code

2019-11-13 09:10 UTC, polyakovartem requested changes

2019-11-13 09:10 UTC, polyakovartem commented on Lab08.py
> +    def duplicates (path:str):
split this function into several smaller functions

2023-04-27 09:34 UTC, closed without merging